projects = { "/workspace" = { trust_level = "trusted" } }

approval_policy = "on-failure"
model_reasoning_effort = "high"
sandbox_mode = "danger-full-access"

[tools]
web_search = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]